#!/bin/bash

set -e

if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install ansible
elif [ -f /etc/debian_version ]; then
    sudo apt-get update
    sudo apt-get install -y software-properties-common ansible git
elif [ -f /etc/fedora-release ]; then
    sudo dnf install -y ansible git
else
    echo "Unsupported OS."
    exit 1
fi

ansible-playbook -i "localhost," -c local playbook.yml
